name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'   # runs once per day (midnight UTC)
  workflow_dispatch:        # allow manual run from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate GitHub Stats
        uses: anuraghazra/github-readme-stats@master
        env:
          PAT_1: ${{ secrets.TEST }}

      - name: Commit and push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Updated GitHub stats"
          git push
